var ten = prompt('Please Enter Your Name')
document.write('Tôi tên là :' + ten)
var email = prompt('Please Enter Your Email')
document.write('<br> Địa chỉ email :' + email)
var sdt = prompt('Please Enter Your Phone Number')
document.write('<br>Đây là số điện thoại của tôi :' + sdt)
var diaChi = prompt('Please Enter Your Address')
document.write('<br>Đây là địa chỉ nhà tôi :' + diaChi)
var skype = prompt('Please Enter Your Skype')
document.write('<br>Đây là skype của tôi :' +skype)